name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - '.github/*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - '.github/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Build default package
        run: nix build .#default
